load("//tools/build/rules:genfile.bzl", "genfile")

genfile(
    name = "presubmit",
    src = "//configs/prow:presubmit.yaml",
    out = "presubmit.yaml",
)

genfile(
    name = "postsubmit",
    src = "//configs/prow:postsubmit.yaml",
    out = "postsubmit.yaml",
)
