package(
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "pgp_public_key",
    srcs = ["pgp-public-key.asc"],
)

filegroup(
    name = "rootca",
    srcs = ["rootca.crt"],
)

filegroup(
    name = "ssh_public_key",
    srcs = ["ssh-public-key.pub"],
)
