load(":defs.bzl", "bsl_binary")

bsl_binary(
    name = "bootstrap",
    srcs = ["bootstrap.bsl"],
)

bsl_binary(
    name = "existential_type",
    srcs = ["existential_type.bsl"],
)

bsl_binary(
    name = "gadt",
    srcs = ["gadt.bsl"],
)

bsl_binary(
    name = "higher_kinded_types",
    srcs = ["higher_kinded_types.bsl"],
)

bsl_binary(
    name = "higher_rank",
    srcs = ["higher_rank.bsl"],
)

bsl_binary(
    name = "rec_and_lazy",
    srcs = ["rec_and_lazy.bsl"],
)

bsl_binary(
    name = "sort",
    srcs = ["sort.bsl"],
)

bsl_binary(
    name = "sort_improved",
    srcs = ["sort_improved.bsl"],
)

bsl_binary(
    name = "std",
    srcs = ["std.bsl"],
)
