postsubmits:
  - name: "postsubmit-bazel-test-all"
    branches:
      - main
      - ^v\d+
    decorate: true
    always_run: true
    skip_report: false
    labels:
      use-cache.k3s.cuhk.servers.boleyn.su: "true"
    spec:
      initContainers:
        - image: quay.io/boleynsu/ci-runner
          command:
            - chown
            - 1000:1000
            - /home/ci-runner/.cache
          securityContext:
            runAsUser: 0
      containers:
        - image: quay.io/boleynsu/ci-runner
          command:
            - bazel
            - test
            - --config=ci-build-and-test
            - //...
          resources:
            limits:
              memory: 1.5Gi
              cpu: 1000m
            requests:
              memory: 512Mi
              cpu: 500m
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  use-cache.k3s.cuhk.servers.boleyn.su: "true"
              topologyKey: kubernetes.io/hostname
