presubmits:
  - name: "presubmit-bazel-test-all"
    branches:
      - main
    decorate: true
    always_run: true
    skip_report: false
    labels:
      use-cache.k3s.cuhk.servers.boleyn.su: "true"
    spec:
      containers:
        - image: quay.io/boleynsu/ci-runner
          command:
            - bazel
            - test
            - --config=ci-build-and-test
            - //...
          resources:
            limits:
              memory: 1.5Gi
              cpu: 1000m
            requests:
              memory: 512Mi
              cpu: 500m
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  use-cache.k3s.cuhk.servers.boleyn.su: "true"
              topologyKey: kubernetes.io/hostname
  - name: "presubmit-deploy-oj-to-staging"
    branches:
      - main
    decorate: true
    always_run: true
    skip_report: false
    labels:
      use-cache.k3s.cuhk.servers.boleyn.su: "true"
      use-ghcr.k3s.cuhk.servers.boleyn.su: "true"
    spec:
      containers:
        - image: quay.io/boleynsu/ci-runner
          command:
            - bazel
            - run
            - --config=ci-deploy
            - //deploy/oj:staging.apply
            - --
            - --server-side
            - --cluster=
          resources:
            limits:
              memory: 1.5Gi
              cpu: 1000m
            requests:
              memory: 512Mi
              cpu: 500m
      serviceAccountName: oj-staging-deployer
      automountServiceAccountToken: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  use-cache.k3s.cuhk.servers.boleyn.su: "true"
              topologyKey: kubernetes.io/hostname
