presubmits:
  - name: "bazel-test-all"
    branches:
      - main
    decorate: true
    always_run: true
    skip_report: false
    labels:
      use-cache.k3s.cuhk.servers.boleyn.su: "true"
    spec:
      containers:
        - image: quay.io/boleynsu/ci-runner
          command:
            - bazel
            - test
            - --config=remote
            - //...
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  use-cache.k3s.cuhk.servers.boleyn.su: "true"
              topologyKey: kubernetes.io/hostname
  - name: "deploy-oj-to-staging"
    branches:
      - main
    decorate: true
    always_run: true
    skip_report: false
    labels:
      use-cache.k3s.cuhk.servers.boleyn.su: "true"
      use-ghcr.k3s.cuhk.servers.boleyn.su: "true"
    spec:
      containers:
        - image: quay.io/boleynsu/ci-runner
          command:
            - bazel
            - run
            - --config=remote
            - "-c"
            - opt
            - //deploy/oj:staging.apply
            - --
            - --server-side
            - --cluster=
      serviceAccountName: oj-staging-deployer
      automountServiceAccountToken: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  use-cache.k3s.cuhk.servers.boleyn.su: "true"
              topologyKey: kubernetes.io/hostname
