apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oj-pv-claim
  labels:
    k8s.boleyn.su/backup: restic
  annotations:
    k8s.boleyn.su/backup-include: "db data filebrowser-conf"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
