apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oj-pv-claim
  labels:
    k8s.boleyn.su/backup: restic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
