FROM docker.io/library/maven@sha256:fedcf9148b713e68fde2a663e311f99cee136b866c9ae843132bcbe3928245ed AS builder
RUN microdnf install -y gcc
WORKDIR /cache
COPY ./pom.xml ./
COPY ./oj-c99runner/pom.xml ./oj-c99runner/
COPY ./oj-core/pom.xml ./oj-core/
COPY ./oj-judge/pom.xml ./oj-judge/
COPY ./oj-server/pom.xml ./oj-server/
RUN mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
WORKDIR /build
COPY ./ ./

RUN mvn package
RUN mkdir -p out
RUN mvn help:evaluate -q -Dexpression=project.version -DforceStdout > out/version
RUN mv oj-c99runner/target/oj-c99runner-$(cat out/version)-jar-with-dependencies.jar out/oj-c99runner.jar

FROM docker.io/library/openjdk:11-jre@sha256:331488bf8ecda52620393aad8260b019337aac038af9a448e7981eb69968f534
RUN apt update && apt install -y gcc && apt clean
COPY --from=builder /build/out /oj-c99runner

RUN useradd -r oj-c99runner
USER oj-c99runner
EXPOSE 1993

ENV RUNNER_ADDRESS 0.0.0.0
ENV RUNNER_PORT 1993

CMD java -jar /oj-c99runner/oj-c99runner.jar
